### ISSUE TITLE
Interface incompatibility

### ISSUE THREAD

**Issue by weargoggles** [avinetworks/terraform-provider-avi#101]
When running a `terraform plan` the provider panics converting a Pool object. AVI 18.1.5.

```

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 198 [running]:
github.com/avinetworks/terraform-provider-avi/avi.SetDefaultsInAPIRes(0x1819e80, 0xc4205f2f90, 0x1819e80, 0xc4205f2ff0, 0xc4203bb770, 0x0, 0x0, 0xc42065d400, 0x29)
	/Users/pwildsmith/go/src/github.com/avinetworks/terraform-provider-avi/avi/utils.go:123 +0xcf7
github.com/avinetworks/terraform-provider-avi/avi.ApiRead(0xc4201ae770, 0x1791360, 0xc42019e900, 0x19177fe, 0x4, 0xc4203bb770, 0xc4207109d0, 0x1012d58)
	/Users/pwildsmith/go/src/github.com/avinetworks/terraform-provider-avi/avi/utils.go:344 +0x667
github.com/avinetworks/terraform-provider-avi/avi.ResourceAviPoolRead(0xc4201ae770, 0x1791360, 0xc42019e900, 0x0, 0x1df7aa0)
	/Users/pwildsmith/go/src/github.com/avinetworks/terraform-provider-avi/avi/resource_avi_pool.go:292 +0x69
github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420834900, 0xc42030fef0, 0x1791360, 0xc42019e900, 0xc42089c588, 0xc4203ba701, 0x80000000018)
	/Users/pwildsmith/go/src/github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:321 +0x199
github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420281c70, 0xc42030fea0, 0xc42030fef0, 0x27006c8, 0x0, 0x18)
	/Users/pwildsmith/go/src/github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:284 +0x9a
github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420229240, 0xc420660c00, 0xc420660cd0, 0x0, 0x0)
	/Users/pwildsmith/go/src/github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
reflect.Value.call(0xc4205563c0, 0xc420224778, 0x13, 0x191725a, 0x4, 0xc420710f20, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc4205563c0, 0xc420224778, 0x13, 0xc42063f720, 0x3, 0x3, 0xc420538660, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420512880, 0xc4208d0910, 0xc420018ec0, 0xc42022ed80, 0xc42055f980, 0x179e2e0, 0xc420660c00, 0x16, 0x179e320, 0xc420660cd0, ...)
	/usr/local/go/src/net/rpc/server.go:381 +0x142
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:475 +0x36b

```

**Comment by gitshrikant** [comment]
@weargoggles Hi,

Can you please try with the latest AVI Provider (18.2.1)? Let me know if you face the same issue.

**Comment by weargoggles** [comment]
Hi @gitshrikant I was using a build from HEAD, and the version I mentioned was the version of the controller. I have rebuilt the provider from the 18.2.1 tag and the problem persists.

**Comment by weargoggles** [comment]
I had installed the newly built provider binary in the directory of my 0.11.8 version of Terraform. This project is using 0.11.7, and when I installed the provider binary in the correct directory my problem went away.

Thanks for the help, I needed the push to recheck it!
